language: node_js
node_js:
  - "12"
script:
  - npm run style
notifications:
  email:
    recipients:
     - wenceslauslee@gmail.com
    on_success: change  # default: change
    on_failure: always  # default: always
deploy:
  - provider: lambda
    function_name: AlexaCovidReport
    region: us-east-1
    role: arn:aws:iam::262375365616:role/service-role/AlexaCovidReport-role-j6o5bqhy
    runtime: nodejs12.x
    module_name: src/index
    handler_name: handler
    description: Alexa skill to report daily COVID-19 reports
    memory_size: 256
    access_key_id:
      secure: QTDXVfX5BMw/FjcZ54emih38EUbz7Ql4ss57n3cHR2uu1R2GJrEXbmFHlwGUmpFSsLk4FzSN1D8YVttlALhYGegvOiER8HcF1gUhXv3g6LO/HiRIU5YHXWoUlrvVlEOKdlpfMWkrFE6trDswcktDW/k2+CJ1nWK49pZQjmDGWQyxNyw1LRUeEAdRSQQNU59B1LeT6Og0Xs/qcgDLbR78+ag2K9DVqNqpMGrxxYePX0jbIw9EubVsH0Y2LM0sSokJdUqmPSpOM21BybGzS3nCsotKf8PbE8J2mbMjVef7GR254hypP66G7VpTj0xWT7pA5KaDACpFSDY4gyeI66bzfivDkHkejRr2CWP+vgkN4bmc9CY09UyLbnoTXlKt1Ub7Iq8h/CMtLImmCTQVj+lUhSwn3oVSWTLqJmNzvwLK/FOzeicskpC6QAi3mMdN4ODik4VLzGTTut5PsiVUuEdPgFAqveqU9Q2sDPjRULhsY8/eZ4YBHr8N2a0iQp0Q9Fa8pB7VQHgIgLfC0utp7Tb1W/Tg/wI76leKITRWh6f/Xhrxn8/UiPZKJMVv+Im1JUdRbcIjTuVtLzfKD758vtYVDQHVp7KqvpUEqZTMRLBO4a07/+Z2YaYHmKyEKgAYUy9YSriZU5pfcaP7MzO45h+1gk3eF3P95D8wpJOKG/9q9R0=
    secret_access_key:
      secure: FkqJgUxixMvV0jGshnpOnE2OqrFAxEpUPPC1y13+tWC8jkPSvbX1M2mwuTjkfmnnRMSxYJJbIxWBu0q3FJnhsgV7dgQF96lWevCN7Qa8jODB95Fl2wpAJt4tW8q5sMqeHROCP8crd1oyNQqXk1nAVNrn5j+9yi2oSb1YsI3q2s0a8WC8vnYzrSMW1mLkBOyzhcNfrpH0zjC4zlhxckOStPAfPj3cli/BX79z5Y22BxL/XkUjFkhwbROvCGiQ0Pw8e4vf6Fw6R5crngLO63PQDVpTqgmv17AJu1aEL9b2ufIyLDLxAeneIpocy8knEGRHBo1DXFR0Odb6f4E52SsMT8acK9NgMkc3l+3HiL/d+g6VKyzrSNTgWNAU7onJYzE4xXCnfuknYd8EvccehumwUaygc9t+8zDpMwhY4gU1IL36sw7KgY0hlNfqKFENV9qo3zDXEAUZ2cQp7YvHKT07uzzsEegLC4WFw5mVbLRu3w/fXyH6E/sPoDkNqonpvmygAHMyiQbtkrjUetD8qX/QiwQ3dsO89B96Dx+ucBZmxq/XqN39Da0EsC12d+GTqV+a0j4hM5XeTbf/S/mt/vvrNCKMcdL0bBNmKTK10PVl7VSLvQq8Xx4XIBvTSdvKRLKd0cI0CZKP4+k8P8I6ZdcPG+t12fMCc4fiiuIYD1i2llY=
    on:
      branch: master
  - provider: lambda
    function_name: AlexaCovidReportDev
    region: us-east-1
    role: arn:aws:iam::262375365616:role/service-role/AlexaCovidReport-role-j6o5bqhy
    runtime: nodejs12.x
    module_name: src/index
    handler_name: handler
    description: Alexa skill to report daily COVID-19 reports
    memory_size: 256
    access_key_id:
      secure: QTDXVfX5BMw/FjcZ54emih38EUbz7Ql4ss57n3cHR2uu1R2GJrEXbmFHlwGUmpFSsLk4FzSN1D8YVttlALhYGegvOiER8HcF1gUhXv3g6LO/HiRIU5YHXWoUlrvVlEOKdlpfMWkrFE6trDswcktDW/k2+CJ1nWK49pZQjmDGWQyxNyw1LRUeEAdRSQQNU59B1LeT6Og0Xs/qcgDLbR78+ag2K9DVqNqpMGrxxYePX0jbIw9EubVsH0Y2LM0sSokJdUqmPSpOM21BybGzS3nCsotKf8PbE8J2mbMjVef7GR254hypP66G7VpTj0xWT7pA5KaDACpFSDY4gyeI66bzfivDkHkejRr2CWP+vgkN4bmc9CY09UyLbnoTXlKt1Ub7Iq8h/CMtLImmCTQVj+lUhSwn3oVSWTLqJmNzvwLK/FOzeicskpC6QAi3mMdN4ODik4VLzGTTut5PsiVUuEdPgFAqveqU9Q2sDPjRULhsY8/eZ4YBHr8N2a0iQp0Q9Fa8pB7VQHgIgLfC0utp7Tb1W/Tg/wI76leKITRWh6f/Xhrxn8/UiPZKJMVv+Im1JUdRbcIjTuVtLzfKD758vtYVDQHVp7KqvpUEqZTMRLBO4a07/+Z2YaYHmKyEKgAYUy9YSriZU5pfcaP7MzO45h+1gk3eF3P95D8wpJOKG/9q9R0=
    secret_access_key:
      secure: FkqJgUxixMvV0jGshnpOnE2OqrFAxEpUPPC1y13+tWC8jkPSvbX1M2mwuTjkfmnnRMSxYJJbIxWBu0q3FJnhsgV7dgQF96lWevCN7Qa8jODB95Fl2wpAJt4tW8q5sMqeHROCP8crd1oyNQqXk1nAVNrn5j+9yi2oSb1YsI3q2s0a8WC8vnYzrSMW1mLkBOyzhcNfrpH0zjC4zlhxckOStPAfPj3cli/BX79z5Y22BxL/XkUjFkhwbROvCGiQ0Pw8e4vf6Fw6R5crngLO63PQDVpTqgmv17AJu1aEL9b2ufIyLDLxAeneIpocy8knEGRHBo1DXFR0Odb6f4E52SsMT8acK9NgMkc3l+3HiL/d+g6VKyzrSNTgWNAU7onJYzE4xXCnfuknYd8EvccehumwUaygc9t+8zDpMwhY4gU1IL36sw7KgY0hlNfqKFENV9qo3zDXEAUZ2cQp7YvHKT07uzzsEegLC4WFw5mVbLRu3w/fXyH6E/sPoDkNqonpvmygAHMyiQbtkrjUetD8qX/QiwQ3dsO89B96Dx+ucBZmxq/XqN39Da0EsC12d+GTqV+a0j4hM5XeTbf/S/mt/vvrNCKMcdL0bBNmKTK10PVl7VSLvQq8Xx4XIBvTSdvKRLKd0cI0CZKP4+k8P8I6ZdcPG+t12fMCc4fiiuIYD1i2llY=
    on:
      branch: development
